### ISSUE TITLE
프로젝트 초기 세팅

### ISSUE THREAD

**Issue by dlwltn0430** [kakao-tech-campus-2nd-step3/Team13_FE#1]
## 💡 개요

개발을 시작하기에 앞서, 템플릿 생성 및 프로젝트 초기 세팅이 필요하다. 

## ✅ To-do

- [x] 이슈 템플릿 생성
- [x] PR 템플릿 생성 
- [x] 프로젝트 생성 및 필요한 모듈 설치 
- [x] `reset.css` 적용
- [x] eslint, prettier 적용
- [x] `.gitignore` 작성
- [x] 이슈, PR용 라벨 생성
- [x] 폴더 구조 설정
