### ISSUE TITLE
[기능 요청] 요양관리사 차트 남은 화면 구현 및 화면간 연결

### ISSUE THREAD

**Issue by nnoonjy** [kakao-tech-campus-2nd-step3/Team13_FE#33]
## 💡 개요

요양관리사가 작성하는 차트의 남은 화면을 구현하고 api를 연결합니다.

## ✅ To-do

- [x] 남은 화면 구현
- [x] 화면간 연결
- [x] 입력값 localStorage에 저장
- [x] 단계 클릭시 이동 가능하게 함
