### ISSUE TITLE
[기능 요청] 음성 녹음 화면 구현

### ISSUE THREAD

**Issue by dlwltn0430** [kakao-tech-campus-2nd-step3/Team13_FE#58]
## 💡 개요

음성 녹음 화면 구현

## ✅ To-do

- [x] Speech to Text UI 구현
- [x] 녹음 중 애니메이션 효과 구현
- [x] 다시 녹음하기 기능 구현
- [x] 녹음 후 내용 수정할 수 있는 UI 구현
