### ISSUE TITLE
[기능 요청] 촬영/음성 녹음 기능 구현 및 녹음/일지 조회 화면 퍼블리싱

### ISSUE THREAD

**Issue by dlwltn0430** [kakao-tech-campus-2nd-step3/Team13_FE#6]
## 💡 개요

아직 API 명세가 정확하게 정해지지 않았기 때문에 확정된 기능 위주로 먼저 구현하고 퍼블리싱을 시작하고자 한다.

## ✅ To-do

- [x] 촬영 기능 구현
- [x] 음성 녹음 기능 구현
- [x] 피요양자 일지 조회 화면 퍼블리싱
