### ISSUE TITLE
[기능 요청] OCR 화면 퍼블리싱 및 API 연결

### ISSUE THREAD

**Issue by dlwltn0430** [kakao-tech-campus-2nd-step3/Team13_FE#74]
## 💡 개요

OCR 화면 퍼블리싱 및 API 연결

## ✅ To-do

- [x] presigned url을 통한 이미지 업로드 구현
- [x] 이미지 업로드 후 텍스트 추출하는 API 연결
- [x] OCR로 인식한 표 수정할 수 있는 화면 퍼블리싱 
- [x] 차트 등록 API 연결
