### ISSUE TITLE
[리팩토링] 사사소소한 수정

### ISSUE THREAD

**Issue by nnoonjy** [kakao-tech-campus-2nd-step3/Team13_FE#75]
## 💡 개요

회의때 나온 내용들을 기반으로 자잘한 수정을 합니다.

## ✅ To-do

- [x] 관리자 및 요양원 로그아웃
- [x] 관리자 및 요양원 로그인 후 선택페이지 구현
- [x] 차트 등록시 로딩 스피너 구현
- [x] 로고 클릭시 랜딩페이지로
