### ISSUE TITLE
[기능 요청] 테스트코드 작성

### ISSUE THREAD

**Issue by nnoonjy** [kakao-tech-campus-2nd-step3/Team13_FE#88]
## 💡 개요

테스트코드를 작성합니다.

## ✅ To-do

- [x] 데이터 get 해온 뒤 일지 수정란 확인
- [x] 데이터 get 해온 뒤 요양원 목록 확인
- [x] 데이터 get 해온 뒤 요약일지 화면 확인
